services:
  app:
    build:
      context: .
    ports:
      - "4985:4985"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network

  # Example postgres database for demo purposes. Remove this in production.
  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5442:5432"
    volumes:
      - ./example_data/postgres:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  # Service to initialize the demo-database with seed data
  db-init:
    image: postgres:15
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./example_data/seed-postgres.sql:/docker-entrypoint-initdb.d/seed.sql
    command: >
      bash -c "PGPASSWORD=postgres psql -h db -U postgres -d postgres -f /docker-entrypoint-initdb.d/seed.sql"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  example_data: 
