services:
  control-plane:
    image: inferable/control-plane:latest
    container_name: control-plane
    depends_on:
      - postgres
      - redis
    ports:
      - "4000:4000"
    environment:
      DATABASE_URL: "postgresql://inferable:inferable@postgres:5432/inferable"
      DATABASE_SSL_DISABLED: "true"
      REDIS_URL: "redis://redis:6379"
      MANAGEMENT_API_SECRET: ${MANAGEMENT_API_SECRET}
      ANTHROPIC_API_KEY: ${ANTHROPIC_API_KEY}
      COHERE_API_KEY: ${COHERE_API_KEY}
      APP_ORIGIN: "http://localhost:3000"

  postgres:
    image: pgvector/pgvector:pg16
    container_name: postgres
    environment:
      POSTGRES_USER: inferable
      POSTGRES_PASSWORD: inferable
      POSTGRES_DB: inferable
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis
    container_name: redis

volumes:
  pgdata:
