services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: postgres
    environment:
      POSTGRES_USER: inferable
      POSTGRES_PASSWORD: inferable
      POSTGRES_DB: inferable
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"

  elasticmq:
    image: softwaremill/elasticmq-native
    container_name: elasticmq
    configs:
      - source: elasticmq_conf
        target: /opt/elasticmq.conf
    volumes:
      - elasticmqdata:/data
    ports:
      - "9324:9324"
      - "9325:9325"

  # Use the data connector to manage the database
  # https://github.com/inferablehq/inferable/tree/main/data-connector
  # data-connector:
  #   image: inferable/data-connector:latest
  #   environment:
  #     INFERABLE_API_SECRET: ${INFERABLE_API_SECRET}
  #   depends_on:
  #     - postgres
  #   configs:
  #     - source: connector_config
  #       target: /app/config.json

volumes:
  pgdata:
  elasticmqdata:

configs:
  elasticmq_conf:
    content: |
      include classpath("application.conf")

      queues {
        run-process {}
        run-generate-name {}
        email-ingestion {}
        customer-telemetry {}
        external-tool-call {}
        email-ingestion {}
      }

  # connector_config:
  #   content: |
  #     {
  #       "privacyMode": 0,
  #       "approvalMode": 0,
  #       "connectors": [
  #         {
  #           "type": "postgres",
  #           "name": "developmentPostgres",
  #           "connectionString": "postgresql://inferable:inferable@postgres:5432/inferable",
  #           "schema": "public"
  #         }
  #       ]
  #     }
