services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: postgres
    environment:
      POSTGRES_USER: inferable
      POSTGRES_PASSWORD: inferable
      POSTGRES_DB: inferable
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis
    container_name: redis

  elasticmq:
    image: softwaremill/elasticmq-native
    container_name: elasticmq
    configs:
      - source: elasticmq_conf
        target: /opt/elasticmq.conf
    volumes:
      - elasticmqdata:/data

