name: Update Changelog

on:
  push:
    tags:
      - '**'

skip: []  # Allows `[skip ci]` commits

jobs:
  generate_changelog:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Generate a changelog
        uses: orhun/git-cliff-action@v3
        with:
          config: cliff.toml
          args: --verbose
        env:
          OUTPUT: CHANGELOG.md
          GITHUB_REPO: ${{ github.repository }}
      - name: Commit changelog
        uses: EndBug/add-and-commit@v9
        with:
          add: 'CHANGELOG.md'
          message: '[skip ci] chore: Update changelog'
          default_author: github_actions
          push: true
          github_token: ${{ secrets.GITHUB_TOKEN }}
