name: Check SDK Changes

on:
  pull_request:
    branches:
      - main
    paths:
      - 'sdk-*/**'

jobs:
  check-sdk-changes:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check for multiple SDK changes
        run: |
          CHANGED_SDKS=$(git diff --name-only origin/${{ github.base_ref }} | grep -E '^sdk-[^/]+/' | cut -d'/' -f1 | sort -u)
          SDK_COUNT=$(echo "$CHANGED_SDKS" | grep -v '^$' | wc -l)

          if [ "$SDK_COUNT" -gt 1 ]; then
            echo "Error: Changes detected in multiple SDK directories:"
            echo "$CHANGED_SDKS"
            echo "Please limit changes to one SDK at a time."
            exit 1
          fi
