name: Check Package Changes

on:
  pull_request:
    branches:
      - main
    paths:
      - 'sdk-*/**'
      - 'cli/**'

jobs:
  check-package-changes:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check for multiple package changes
        run: |
          CHANGED_PACKAGES=$(git diff --name-only origin/"${{ github.base_ref }}" | grep -E '^(sdk-[^/]+/|cli/)' | cut -d'/' -f1 | sort -u)

          COUNT=$(echo "$CHANGED_PACKAGES" | grep -v '^$' | wc -l)

          echo "$CHANGED_PACKAGES (COUNT=$COUNT)"

          if [ "$COUNT" -gt 1 ]; then
            echo "Error: Changes detected in multiple packages:"
            echo "Please limit changes to one package at a time."
            exit 1
          fi
