name: Check conventional commits

permissions:
  pull-requests: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
  
on:
  pull_request:
    branches:
      - main
    types: [opened, edited, reopened, synchronize, ready_for_review]

jobs:
  commit-message-validation:
    runs-on: ubuntu-latest

    steps:
      - name: Commit message validation
        uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
