name: E2E heartbeat

on:
  schedule:
    - cron: "0 * * * *"
  pull_request:
    branches:
      - main
    paths:
      - 'load-tests/**'

jobs:
  run-e2e:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: load-tests
    env:
      INFERABLE_TEST_CLUSTER_ID: ${{ secrets.INFERABLE_TEST_CLUSTER_ID }}
      INFERABLE_TEST_API_SECRET: ${{ secrets.INFERABLE_TEST_API_SECRET }}
      BETTER_STACK_SYNTHETIC_ENDPOINT: ${{ secrets.BETTER_STACK_SYNTHETIC_ENDPOINT }}
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: npm ci
        # Run machine:start backgrounded
      - run: npm run machine:start &
      - uses: grafana/setup-k6-action@v1
      - uses: grafana/run-k6-action@v1
        with:
          path: ./load-tests/script.js
          fail-fast: true
          flags: --throw
      - run: curl -X POST ${BETTER_STACK_SYNTHETIC_ENDPOINT}
