name: Publish Go SDK

on:
  workflow_dispatch:

jobs:
  publish-go:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    defaults:
      run:
        working-directory: sdk-go
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.22"
      - name: Get current version
        id: get_version
        run: |
          VERSION=$(grep -oP 'const Version = "\K[^"]+' inferable.go)
          echo "current_version=$VERSION" >> $GITHUB_OUTPUT
      - name: Increment patch version
        id: increment_version
        run: |
          IFS='.' read -ra VERSION_PARTS <<< "${{ steps.get_version.outputs.current_version }}"
          MAJOR=${VERSION_PARTS[0]}
          MINOR=${VERSION_PARTS[1]}
          PATCH=$((VERSION_PARTS[2] + 1))
          NEW_VERSION="$MAJOR.$MINOR.$PATCH"
          echo "new_version=$NEW_VERSION" >> $GITHUB_OUTPUT
      - name: Update version in code
        run: |
          sed -i 's/const Version = "[^"]*"/const Version = "${{ steps.increment_version.outputs.new_version }}"/' inferable.go
      - name: Commit and push changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add inferable.go
          git commit -m "Bump version to ${{ steps.increment_version.outputs.new_version }}"
          git push
      - name: Create Git tag
        run: |
          git tag v${{ steps.increment_version.outputs.new_version }}
          git push origin v${{ steps.increment_version.outputs.new_version }}
